services:
  web:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
      - database

  database:
    image: postgres:17.4-alpine
    restart: always
    volumes:
      - ${DB_DATA}:/var/lib/postgres/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
